### ISSUE TITLE
Proof Read: Visual Studio Code

### ISSUE THREAD

**Issue by jcollard** [CaptainCoderOrg/IntroToCSharpSite#121]

**Comment by promiseofwater** [comment]
1. avoiding I "modern software is among the most intricate..."
2.  to works here maybe "in order to manage..." sounds better
3. bold
4. bold
5. bold
6. bold
7. bold
8.  change to "Due to..." or flip sentence structure
9. bold
10. bold
11. bold
12. bold
13. bold




![Image](https://user-images.githubusercontent.com/59033964/186278130-675ca3df-528d-4e20-916b-8ee3045bbe6a.png)

**Comment by promiseofwater** [comment]
1. bold
2. bold
3. bold
4. bold




![Image](https://user-images.githubusercontent.com/59033964/186278324-e6a061a9-9ab4-4299-9393-ec170f36cbad.png)

**Comment by jcollard** [comment]
Updated! Thanks!

**Comment by jcollard** [comment]
Word Count: 555
Link: https://docs.google.com/document/d/1TRATqqRNMRYNv6Xu-XV92i20FL6sFINrnoanhxI2ydw/edit?usp=sharing
